/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

// Key event actions (from input.h)
#define AKEY_EVENT_ACTION_DOWN 0
#define AKEY_EVENT_ACTION_UP 1
#define AKEY_EVENT_ACTION_MULTIPLE 2

// Motion event actions (from input.h)
#define AMOTION_EVENT_ACTION_DOWN 0
#define AMOTION_EVENT_ACTION_UP 1
#define AMOTION_EVENT_ACTION_MOVE 2
#define AMOTION_EVENT_ACTION_CANCEL 3
#define AMOTION_EVENT_ACTION_OUTSIDE 4
#define AMOTION_EVENT_ACTION_POINTER_DOWN 5
#define AMOTION_EVENT_ACTION_POINTER_UP 6
#define AMOTION_EVENT_ACTION_HOVER_MOVE 7
#define AMOTION_EVENT_ACTION_SCROLL 8
#define AMOTION_EVENT_ACTION_HOVER_ENTER 9
#define AMOTION_EVENT_ACTION_HOVER_EXIT 10
#define AMOTION_EVENT_ACTION_BUTTON_PRESS 11
#define AMOTION_EVENT_ACTION_BUTTON_RELEASE 12

// Key codes (from keycodes.h)
#define AKEYCODE_UNKNOWN 0
#define AKEYCODE_SOFT_LEFT 1
#define AKEYCODE_SOFT_RIGHT 2
#define AKEYCODE_HOME 3
#define AKEYCODE_BACK 4
#define AKEYCODE_CALL 5
#define AKEYCODE_ENDCALL 6
#define AKEYCODE_0 7
#define AKEYCODE_1 8
#define AKEYCODE_2 9
#define AKEYCODE_3 10
#define AKEYCODE_4 11
#define AKEYCODE_5 12
#define AKEYCODE_6 13
#define AKEYCODE_7 14
#define AKEYCODE_8 15
#define AKEYCODE_9 16
#define AKEYCODE_STAR 17
#define AKEYCODE_POUND 18
#define AKEYCODE_DPAD_UP 19
#define AKEYCODE_DPAD_DOWN 20
#define AKEYCODE_DPAD_LEFT 21
#define AKEYCODE_DPAD_RIGHT 22
#define AKEYCODE_DPAD_CENTER 23
#define AKEYCODE_VOLUME_UP 24
#define AKEYCODE_VOLUME_DOWN 25
#define AKEYCODE_POWER 26
#define AKEYCODE_CAMERA 27
#define AKEYCODE_CLEAR 28
#define AKEYCODE_A 29
#define AKEYCODE_B 30
#define AKEYCODE_C 31
#define AKEYCODE_D 32
#define AKEYCODE_E 33
#define AKEYCODE_F 34
#define AKEYCODE_G 35
#define AKEYCODE_H 36
#define AKEYCODE_I 37
#define AKEYCODE_J 38
#define AKEYCODE_K 39
#define AKEYCODE_L 40
#define AKEYCODE_M 41
#define AKEYCODE_N 42
#define AKEYCODE_O 43
#define AKEYCODE_P 44
#define AKEYCODE_Q 45
#define AKEYCODE_R 46
#define AKEYCODE_S 47
#define AKEYCODE_T 48
#define AKEYCODE_U 49
#define AKEYCODE_V 50
#define AKEYCODE_W 51
#define AKEYCODE_X 52
#define AKEYCODE_Y 53
#define AKEYCODE_Z 54
#define AKEYCODE_COMMA 55
#define AKEYCODE_PERIOD 56
#define AKEYCODE_ALT_LEFT 57
#define AKEYCODE_ALT_RIGHT 58
#define AKEYCODE_SHIFT_LEFT 59
#define AKEYCODE_SHIFT_RIGHT 60
#define AKEYCODE_TAB 61
#define AKEYCODE_SPACE 62
#define AKEYCODE_SYM 63
#define AKEYCODE_EXPLORER 64
#define AKEYCODE_ENVELOPE 65
#define AKEYCODE_ENTER 66
#define AKEYCODE_DEL 67
#define AKEYCODE_GRAVE 68
#define AKEYCODE_MINUS 69
#define AKEYCODE_EQUALS 70
#define AKEYCODE_LEFT_BRACKET 71
#define AKEYCODE_RIGHT_BRACKET 72
#define AKEYCODE_BACKSLASH 73
#define AKEYCODE_SEMICOLON 74
#define AKEYCODE_APOSTROPHE 75
#define AKEYCODE_SLASH 76
#define AKEYCODE_AT 77
#define AKEYCODE_NUM 78
#define AKEYCODE_HEADSETHOOK 79
#define AKEYCODE_FOCUS 80
#define AKEYCODE_PLUS 81
#define AKEYCODE_MENU 82
#define AKEYCODE_NOTIFICATION 83
#define AKEYCODE_SEARCH 84
#define AKEYCODE_MEDIA_PLAY_PAUSE 85
#define AKEYCODE_MEDIA_STOP 86
#define AKEYCODE_MEDIA_NEXT 87
#define AKEYCODE_MEDIA_PREVIOUS 88
#define AKEYCODE_MEDIA_REWIND 89
#define AKEYCODE_MEDIA_FAST_FORWARD 90
#define AKEYCODE_MUTE 91
#define AKEYCODE_PAGE_UP 92
#define AKEYCODE_PAGE_DOWN 93
#define AKEYCODE_PICTSYMBOLS 94
#define AKEYCODE_SWITCH_CHARSET 95
#define AKEYCODE_BUTTON_A 96
#define AKEYCODE_BUTTON_B 97
#define AKEYCODE_BUTTON_C 98
#define AKEYCODE_BUTTON_X 99
#define AKEYCODE_BUTTON_Y 100
#define AKEYCODE_BUTTON_Z 101
#define AKEYCODE_BUTTON_L1 102
#define AKEYCODE_BUTTON_R1 103
#define AKEYCODE_BUTTON_L2 104
#define AKEYCODE_BUTTON_R2 105
#define AKEYCODE_BUTTON_THUMBL 106
#define AKEYCODE_BUTTON_THUMBR 107
#define AKEYCODE_BUTTON_START 108
#define AKEYCODE_BUTTON_SELECT 109
#define AKEYCODE_BUTTON_MODE 110

// Axis constants (from input.h)
#define AMOTION_EVENT_AXIS_X 0
#define AMOTION_EVENT_AXIS_Y 1
#define AMOTION_EVENT_AXIS_PRESSURE 2
#define AMOTION_EVENT_AXIS_SIZE 3
#define AMOTION_EVENT_AXIS_TOUCH_MAJOR 4
#define AMOTION_EVENT_AXIS_TOUCH_MINOR 5
#define AMOTION_EVENT_AXIS_TOOL_MAJOR 6
#define AMOTION_EVENT_AXIS_TOOL_MINOR 7
#define AMOTION_EVENT_AXIS_ORIENTATION 8
#define AMOTION_EVENT_AXIS_VSCROLL 9
#define AMOTION_EVENT_AXIS_HSCROLL 10
#define AMOTION_EVENT_AXIS_Z 11
#define AMOTION_EVENT_AXIS_RX 12
#define AMOTION_EVENT_AXIS_RY 13
#define AMOTION_EVENT_AXIS_RZ 14
#define AMOTION_EVENT_AXIS_HAT_X 15
#define AMOTION_EVENT_AXIS_HAT_Y 16
#define AMOTION_EVENT_AXIS_LTRIGGER 17
#define AMOTION_EVENT_AXIS_RTRIGGER 18
#define AMOTION_EVENT_AXIS_THROTTLE 19
#define AMOTION_EVENT_AXIS_RUDDER 20
#define AMOTION_EVENT_AXIS_WHEEL 21
#define AMOTION_EVENT_AXIS_GAS 22
#define AMOTION_EVENT_AXIS_BRAKE 23
#define AMOTION_EVENT_AXIS_DISTANCE 24
#define AMOTION_EVENT_AXIS_TILT 25
#define AMOTION_EVENT_AXIS_SCROLL 26
#define AMOTION_EVENT_AXIS_RELATIVE_X 27
#define AMOTION_EVENT_AXIS_RELATIVE_Y 28
#define AMOTION_EVENT_AXIS_GENERIC_1 32
#define AMOTION_EVENT_AXIS_GENERIC_2 33
#define AMOTION_EVENT_AXIS_GENERIC_3 34
#define AMOTION_EVENT_AXIS_GENERIC_4 35
#define AMOTION_EVENT_AXIS_GENERIC_5 36
#define AMOTION_EVENT_AXIS_GENERIC_6 37
#define AMOTION_EVENT_AXIS_GENERIC_7 38
#define AMOTION_EVENT_AXIS_GENERIC_8 39
#define AMOTION_EVENT_AXIS_GENERIC_9 40
#define AMOTION_EVENT_AXIS_GENERIC_10 41
#define AMOTION_EVENT_AXIS_GENERIC_11 42
#define AMOTION_EVENT_AXIS_GENERIC_12 43
#define AMOTION_EVENT_AXIS_GENERIC_13 44
#define AMOTION_EVENT_AXIS_GENERIC_14 45
#define AMOTION_EVENT_AXIS_GENERIC_15 46
#define AMOTION_EVENT_AXIS_GENERIC_16 47