# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/caesar/game-dev/project-bullet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/caesar/game-dev/project-bullet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/caesar/game-dev/project-bullet/CMakeFiles /home/caesar/game-dev/project-bullet//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/caesar/game-dev/project-bullet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vulkan_new

# Build rule for target.
vulkan_new: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vulkan_new
.PHONY : vulkan_new

# fast build rule for target.
vulkan_new/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/build
.PHONY : vulkan_new/fast

imgui-master/backends/imgui_impl_glfw.o: imgui-master/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui-master/backends/imgui_impl_glfw.o

# target to build an object file
imgui-master/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui-master/backends/imgui_impl_glfw.cpp.o

imgui-master/backends/imgui_impl_glfw.i: imgui-master/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui-master/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui-master/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui-master/backends/imgui_impl_glfw.cpp.i

imgui-master/backends/imgui_impl_glfw.s: imgui-master/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui-master/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui-master/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui-master/backends/imgui_impl_glfw.cpp.s

imgui-master/backends/imgui_impl_vulkan.o: imgui-master/backends/imgui_impl_vulkan.cpp.o
.PHONY : imgui-master/backends/imgui_impl_vulkan.o

# target to build an object file
imgui-master/backends/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/backends/imgui_impl_vulkan.cpp.o
.PHONY : imgui-master/backends/imgui_impl_vulkan.cpp.o

imgui-master/backends/imgui_impl_vulkan.i: imgui-master/backends/imgui_impl_vulkan.cpp.i
.PHONY : imgui-master/backends/imgui_impl_vulkan.i

# target to preprocess a source file
imgui-master/backends/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/backends/imgui_impl_vulkan.cpp.i
.PHONY : imgui-master/backends/imgui_impl_vulkan.cpp.i

imgui-master/backends/imgui_impl_vulkan.s: imgui-master/backends/imgui_impl_vulkan.cpp.s
.PHONY : imgui-master/backends/imgui_impl_vulkan.s

# target to generate assembly for a file
imgui-master/backends/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/backends/imgui_impl_vulkan.cpp.s
.PHONY : imgui-master/backends/imgui_impl_vulkan.cpp.s

imgui-master/imgui.o: imgui-master/imgui.cpp.o
.PHONY : imgui-master/imgui.o

# target to build an object file
imgui-master/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui.cpp.o
.PHONY : imgui-master/imgui.cpp.o

imgui-master/imgui.i: imgui-master/imgui.cpp.i
.PHONY : imgui-master/imgui.i

# target to preprocess a source file
imgui-master/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui.cpp.i
.PHONY : imgui-master/imgui.cpp.i

imgui-master/imgui.s: imgui-master/imgui.cpp.s
.PHONY : imgui-master/imgui.s

# target to generate assembly for a file
imgui-master/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui.cpp.s
.PHONY : imgui-master/imgui.cpp.s

imgui-master/imgui_demo.o: imgui-master/imgui_demo.cpp.o
.PHONY : imgui-master/imgui_demo.o

# target to build an object file
imgui-master/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_demo.cpp.o
.PHONY : imgui-master/imgui_demo.cpp.o

imgui-master/imgui_demo.i: imgui-master/imgui_demo.cpp.i
.PHONY : imgui-master/imgui_demo.i

# target to preprocess a source file
imgui-master/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_demo.cpp.i
.PHONY : imgui-master/imgui_demo.cpp.i

imgui-master/imgui_demo.s: imgui-master/imgui_demo.cpp.s
.PHONY : imgui-master/imgui_demo.s

# target to generate assembly for a file
imgui-master/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_demo.cpp.s
.PHONY : imgui-master/imgui_demo.cpp.s

imgui-master/imgui_draw.o: imgui-master/imgui_draw.cpp.o
.PHONY : imgui-master/imgui_draw.o

# target to build an object file
imgui-master/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_draw.cpp.o
.PHONY : imgui-master/imgui_draw.cpp.o

imgui-master/imgui_draw.i: imgui-master/imgui_draw.cpp.i
.PHONY : imgui-master/imgui_draw.i

# target to preprocess a source file
imgui-master/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_draw.cpp.i
.PHONY : imgui-master/imgui_draw.cpp.i

imgui-master/imgui_draw.s: imgui-master/imgui_draw.cpp.s
.PHONY : imgui-master/imgui_draw.s

# target to generate assembly for a file
imgui-master/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_draw.cpp.s
.PHONY : imgui-master/imgui_draw.cpp.s

imgui-master/imgui_tables.o: imgui-master/imgui_tables.cpp.o
.PHONY : imgui-master/imgui_tables.o

# target to build an object file
imgui-master/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_tables.cpp.o
.PHONY : imgui-master/imgui_tables.cpp.o

imgui-master/imgui_tables.i: imgui-master/imgui_tables.cpp.i
.PHONY : imgui-master/imgui_tables.i

# target to preprocess a source file
imgui-master/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_tables.cpp.i
.PHONY : imgui-master/imgui_tables.cpp.i

imgui-master/imgui_tables.s: imgui-master/imgui_tables.cpp.s
.PHONY : imgui-master/imgui_tables.s

# target to generate assembly for a file
imgui-master/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_tables.cpp.s
.PHONY : imgui-master/imgui_tables.cpp.s

imgui-master/imgui_widgets.o: imgui-master/imgui_widgets.cpp.o
.PHONY : imgui-master/imgui_widgets.o

# target to build an object file
imgui-master/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_widgets.cpp.o
.PHONY : imgui-master/imgui_widgets.cpp.o

imgui-master/imgui_widgets.i: imgui-master/imgui_widgets.cpp.i
.PHONY : imgui-master/imgui_widgets.i

# target to preprocess a source file
imgui-master/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_widgets.cpp.i
.PHONY : imgui-master/imgui_widgets.cpp.i

imgui-master/imgui_widgets.s: imgui-master/imgui_widgets.cpp.s
.PHONY : imgui-master/imgui_widgets.s

# target to generate assembly for a file
imgui-master/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/imgui-master/imgui_widgets.cpp.s
.PHONY : imgui-master/imgui_widgets.cpp.s

lib/ui.o: lib/ui.cpp.o
.PHONY : lib/ui.o

# target to build an object file
lib/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/lib/ui.cpp.o
.PHONY : lib/ui.cpp.o

lib/ui.i: lib/ui.cpp.i
.PHONY : lib/ui.i

# target to preprocess a source file
lib/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/lib/ui.cpp.i
.PHONY : lib/ui.cpp.i

lib/ui.s: lib/ui.cpp.s
.PHONY : lib/ui.s

# target to generate assembly for a file
lib/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/lib/ui.cpp.s
.PHONY : lib/ui.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vulkan_new.dir/build.make CMakeFiles/vulkan_new.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vulkan_new"
	@echo "... imgui-master/backends/imgui_impl_glfw.o"
	@echo "... imgui-master/backends/imgui_impl_glfw.i"
	@echo "... imgui-master/backends/imgui_impl_glfw.s"
	@echo "... imgui-master/backends/imgui_impl_vulkan.o"
	@echo "... imgui-master/backends/imgui_impl_vulkan.i"
	@echo "... imgui-master/backends/imgui_impl_vulkan.s"
	@echo "... imgui-master/imgui.o"
	@echo "... imgui-master/imgui.i"
	@echo "... imgui-master/imgui.s"
	@echo "... imgui-master/imgui_demo.o"
	@echo "... imgui-master/imgui_demo.i"
	@echo "... imgui-master/imgui_demo.s"
	@echo "... imgui-master/imgui_draw.o"
	@echo "... imgui-master/imgui_draw.i"
	@echo "... imgui-master/imgui_draw.s"
	@echo "... imgui-master/imgui_tables.o"
	@echo "... imgui-master/imgui_tables.i"
	@echo "... imgui-master/imgui_tables.s"
	@echo "... imgui-master/imgui_widgets.o"
	@echo "... imgui-master/imgui_widgets.i"
	@echo "... imgui-master/imgui_widgets.s"
	@echo "... lib/ui.o"
	@echo "... lib/ui.i"
	@echo "... lib/ui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

